### ISSUE TITLE
Name change to reflect general cryptocurrency mining detection?

### ISSUE THREAD

**Issue by michaelsmitasin** [jsiwek/zeek-cryptomining#2]
We're big fans of this package - we've been running it for a while now and have detected several infected machines as a result of it. I noticed it's capable of detecting other cryptocurrencies besides Bitcoin, would it make sense to generalize the name of the package (and references in the scripts) from "Bitcoin" to "CryptoMining"?

Thanks!

**Comment by jsiwek** [comment]
I've renamed the repo/package to `zeek-cryptomining`.  The rename shouldn't break existing installs (they'll still receive updates via `zkg`).

Renaming the Zeek module/namespace from "Bitcoin" would potentially break user scripts/customizations, so more reluctant to do that.
