### ISSUE TITLE
How to use it 

### ISSUE THREAD

**Issue by TerenceLiu98** [jsiwek/zeek-cryptomining#3]
Hello, I am curious about how to use this script. I am a admin of a cluster and I am wonder if you may teach me how to use it. For now, I just downloaded, installed, and loaded the `zeek-cryptomining` but how I know whether their is a mining programming or script ? 

Looking forware to your reply!

**Comment by jsiwek** [comment]
If you're using `ZeekControl` with properly configured `${zeek_prefix}/etc/networks.cfg`, then it automatically emits entries into `notice.log` on detecting various mining activity on the local network.  The names of those `notice.log` types:

* `Bitcoin::Miner`
* `Bitcoin::Mining_Pool_Server`
* `Bitcoin::Possible_Mining`

The name `Bitcoin` in those notices isn't actually indicative of the "Bitcoin" cryptocurrency in particular, it's just coming from a time when "Bitcoin" was the main/relevant one.
