### ISSUE TITLE
Does this plugin work with TLS enabled?

### ISSUE THREAD

**Issue by ichetty** [jsiwek/zeek-cryptomining#5]
@jsiwek I have a couple of questions.
1. How do I verify that this plugin is loaded and working? is there a simple test?
2. Does this plugin work when TLS is enabled? for example xmrig with TLS

**Comment by jsiwek** [comment]
> * How do I verify that this plugin is loaded and working? is there a simple test?

`loaded_scripts.log` can help verify what's actually loaded.

There's a couple test scripts in this repo:

https://github.com/jsiwek/zeek-cryptomining/tree/master/testing/tests

that show how to run on associated offline pcap files that contain some mining traffic:

https://github.com/jsiwek/zeek-cryptomining/tree/master/testing/Traces

and may help verify your setup works (at least for the kind of traffic in the those pcaps).

> * Does this plugin work when TLS is enabled? for example xmrig with TLS

I'm not familiar with how xmrig works, but typically this plugin can't know about anything inside TLS unless you've somehow arranged for Zeek to receive decrypted traffic or configured it to decrypt some limited cases (documented at https://docs.zeek.org/en/master/frameworks/tls-decryption.html).
